import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/CtaBand";
import { divisions } from "@/lib/site";

export default function Home() {
  return <>
    <section className="home-hero"><Image className="home-hero-image" src="https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=2200&q=85" alt="Profesionální úklid ve firemním provozu" fill priority sizes="100vw" /><div className="hero-shade" /><div className="hero-grid" /><div className="home-hero-copy"><p className="eyebrow light"><span />Česká firma s více než 30letou zkušeností</p><h1>Tři divize.<br /><em>Jeden silný partner.</em></h1><p>Technologie, servis a stavební práce pro firmy, které potřebují, aby jejich provoz fungoval bez kompromisů.</p><div className="hero-actions"><Link className="button button-lime" href="#divize">Prozkoumat služby <span>↓</span></Link><a className="button button-outline" href="tel:+420606657161">Zavolat +420 606 657 161</a></div></div><div className="hero-stats"><div><strong>30+</strong><span>let na českém trhu</span></div><div><strong>3</strong><span>specializované divize</span></div><div><strong>ČR</strong><span>servis po celé republice</span></div></div></section>
    <section className="division-section" id="divize"><div className="section-label">01 / Co pro vás zajistíme</div><div className="section-intro"><h2>Jeden kontakt.<br />Tři obory expertizy.</h2><p>Od výběru profesionální techniky přes její dlouhodobý servis až po specializované stavební zásahy. FISPOGROUP propojuje zkušenosti, které drží váš provoz v pohybu.</p></div><div className="division-grid">{divisions.map((division) => <Link className={`division-card ${division.color}`} href={division.href} key={division.href}><div><span>{division.number}</span><span>↗</span></div><p>{division.short}</p><h3>{division.title}</h3><small>{division.text}</small><b>Zjistit více <span>→</span></b></Link>)}</div></section>
    <section className="home-proof"><div className="proof-image"><Image src="https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1500&q=85" alt="Technik při odborném servisu" fill sizes="(max-width: 900px) 100vw, 50vw" /></div><div className="proof-copy"><p className="eyebrow"><span />Partnerství, které nekončí nákupem</p><h2>Dodáme řešení.<br /><em>A postaráme se o něj.</em></h2><p>Rozumíme tomu, že technika i provoz musí fungovat každý den. Proto spojujeme odborný výběr, rychlou dostupnost, servisní podporu a školení.</p><ul><li><span>01</span>Osobní konzultace a návrh vhodného řešení</li><li><span>02</span>Záruční i pozáruční servis napříč značkami</li><li><span>03</span>Pobočky v Praze, Brně a Opavě</li></ul><Link href="/o-spolecnosti">Poznejte FISPOGROUP <span>→</span></Link></div></section>
    <CtaBand title="Co pro vás můžeme udělat?" />
  </>;
}
